[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "canvas fluid pole destroy immense text blind blade clutch defense question delay minor liquid garlic question recycle basket often crew bounce sentence apology keen"
